[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.35", features = ["derive"] }
futures-util = "0.3.31"
mini-moka = "0.10.3"
nanoid = "0.4.0"
rand = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_repr = "0.1.20"
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.44.2", features = ["full"] }
traccia = { version = "2.2.1", features = ["clap"] }
fastwebsockets = { version = "0.10.0", features = ["unstable-split", "upgrade"] }
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["server"] }
hyper-util = { version = "0.1.11", features = ["tokio"] }
anyhow = "1.0.97"
async-trait = "0.1.88"
