[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.35", features = ["derive"] }
futures-util = "0.3.31"
hyper = "1.6.0"
mini-moka = "0.10.3"
nanoid = "0.4.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_repr = "0.1.20"
tokio = { version = "1.44.2", features = ["full"] }
tokio-tungstenite = "0.26.2"
traccia = { version = "2.2.1", features = ["clap"] }
