[package]
name = "relay"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
clap = { version = "4.5.37", features = ["derive"] }
fastwebsockets = "0.10.0"
tokio = { version = "1.45.0", features = ["full"] }
traccia = "2.2.1"
