[package]
name = "console"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
termios = "0.3.3"
tokio = { version = "1.44.2", features = ["io-std", "io-util"] }

[dev-dependencies]
tokio = { version = "1.44.2", features = ["full"] }